fix: decomment debian-images

diff --git a/.github/workflows/multi-platform.yml b/.github/workflows/multi-platform.yml
--- a/.github/workflows/multi-platform.yml
+++ b/.github/workflows/multi-platform.yml
@@ -32,7 +32,7 @@ jobs:
           - ubuntu-24.04-arm
         img:
           - alpine-3.10
-          - debian-3.10
+          # - debian-3.10
         include:
           - runner: ubuntu-latest
             platform: linux/amd64
@@ -48,12 +48,11 @@ jobs:
               akira25/gnuradio-docker-container:latest
             #  ghcr.io/akira25/gnuradio-docker-container:3.10-alpine
             #  ghcr.io/akira25/gnuradio-docker-container:latest
-          - img: debian-3.10
-            base_os: debian
-            context: ./debian/3.10/
-            tags: |
-              akira25/gnuradio-docker-container:3.10-debian
-            #  ghcr.io/akira25/gnuradio-docker-container:3.10-debian
+          # - img: debian-3.10
+            # base_os: debian
+            # context: ./debian/3.10/
+            # tags: |
+              # akira25/gnuradio-docker-container:3.10-debian
 
     runs-on: ${{ matrix.runner }}
     permissions:
@@ -128,11 +127,11 @@ jobs:
               ${{ env.DHUB_REGISTRY }}/${{ env.DHUB_REPO }}:${{ env.GR_VERSION }}-amd64-alpine \
               ${{ env.DHUB_REGISTRY }}/${{ env.DHUB_REPO }}:${{ env.GR_VERSION }}-arm64-alpine
           done
-          for tag in ${{ env.GR_VERSION }}-debian; do
-            docker buildx imagetools create -t ${{ env.DHUB_REGISTRY }}/${{ env.DHUB_REPO }}:${tag} \
-              ${{ env.DHUB_REGISTRY }}/${{ env.DHUB_REPO }}:${{ env.GR_VERSION }}-amd64-debian \
-              ${{ env.DHUB_REGISTRY }}/${{ env.DHUB_REPO }}:${{ env.GR_VERSION }}-arm64-debian
-          done
+          #for tag in ${{ env.GR_VERSION }}-debian; do
+          #  docker buildx imagetools create -t ${{ env.DHUB_REGISTRY }}/${{ env.DHUB_REPO }}:${tag} \
+          #    ${{ env.DHUB_REGISTRY }}/${{ env.DHUB_REPO }}:${{ env.GR_VERSION }}-amd64-debian \
+          #    ${{ env.DHUB_REGISTRY }}/${{ env.DHUB_REPO }}:${{ env.GR_VERSION }}-arm64-debian
+          #done
 
       - name: Log in to ghcr.io
         uses: docker/login-action@v3
@@ -148,11 +147,11 @@ jobs:
               ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPO }}:${{ env.GR_VERSION }}-amd64-alpine \
               ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPO }}:${{ env.GR_VERSION }}-arm64-alpine
           done
-          for tag in ${{ env.GR_VERSION }}-debian; do
-            docker buildx imagetools create -t ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPO }}:${tag} \
-              ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPO }}:${{ env.GR_VERSION }}-amd64-debian \
-              ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPO }}:${{ env.GR_VERSION }}-arm64-debian
-          done
+          #for tag in ${{ env.GR_VERSION }}-debian; do
+          #  docker buildx imagetools create -t ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPO }}:${tag} \
+          #    ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPO }}:${{ env.GR_VERSION }}-amd64-debian \
+          #    ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPO }}:${{ env.GR_VERSION }}-arm64-debian
+          #done
 
       - name: Cleanup Platform Tags (Dockerhub)
         run: |
@@ -167,17 +166,17 @@ jobs:
             curl -X DELETE -H "Authorization: Bearer ${TOKEN}" ${IMAGE_URL} || echo "Failed to delete ${arch} tag"
           done
 
-          # delete debian-intermediate tags
-          for arch in amd64 arm64; do
-            IMAGE_URL="https://hub.docker.com/v2/repositories/${{ env.DHUB_REPO }}/tags/${{ env.GR_VERSION }}-${arch}-debian/"
-            curl -X DELETE -H "Authorization: Bearer ${TOKEN}" ${IMAGE_URL} || echo "Failed to delete ${arch} tag"
-          done
+          ## delete debian-intermediate tags
+          #for arch in amd64 arm64; do
+          #  IMAGE_URL="https://hub.docker.com/v2/repositories/${{ env.DHUB_REPO }}/tags/${{ env.GR_VERSION }}-${arch}-debian/"
+          #  curl -X DELETE -H "Authorization: Bearer ${TOKEN}" ${IMAGE_URL} || echo "Failed to delete ${arch} tag"
+          #done
 
-      - name: Cleanup Platform Tags (ghcr)
-        run: |
-          set -e
-          .github/workflows/scripts/ghcr-prune.py --container gnuradio-docker-container --prune-tag arm64 --prune-age 7
-          .github/workflows/scripts/ghcr-prune.py --container gnuradio-docker-container --prune-tag amd64 --prune-age 7
+      #- name: Cleanup Platform Tags (ghcr)
+      #  run: |
+      #    set -e
+      #    .github/workflows/scripts/ghcr-prune.py --container gnuradio-docker-container --prune-tag arm64 --prune-age 7
+      #    .github/workflows/scripts/ghcr-prune.py --container gnuradio-docker-container --prune-tag amd64 --prune-age 7
 
       #- name: Verify Image
       #  uses: addnab/docker-run-action@v3
