feature: cleanup ghcr intermediate tags

diff --git a/.github/workflows/multi-platform.yml b/.github/workflows/multi-platform.yml
--- a/.github/workflows/multi-platform.yml
+++ b/.github/workflows/multi-platform.yml
@@ -154,7 +154,7 @@ jobs:
               ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPO }}:${{ env.GR_VERSION }}-arm64-debian
           done
 
-      - name: Cleanup Platform Tags
+      - name: Cleanup Platform Tags (Dockerhub)
         run: |
           set -e
           TOKEN=$(curl -s -X POST -H "Content-Type: application/json" \
@@ -171,6 +171,40 @@ jobs:
           for arch in amd64 arm64; do
             IMAGE_URL="https://hub.docker.com/v2/repositories/${{ env.DHUB_REPO }}/tags/${{ env.GR_VERSION }}-${arch}-debian/"
             curl -X DELETE -H "Authorization: Bearer ${TOKEN}" ${IMAGE_URL} || echo "Failed to delete ${arch} tag"
+          done
+
+      - name: Cleanup Platform Tags (ghcr)
+        run: |
+          set -e
+          TOKEN=${{ secrets.GHCR_PAT }}
+          OWNER=${{ github.repository_owner }}
+
+          # delete alpine-intermediate tags
+          for arch in amd64 arm64; do
+            IMAGE_URL="https://ghcr.io/v2/${OWNER}/${{ env.GHCR_REPO }}/manifests/${{ env.GR_VERSION }}-${arch}-alpine"
+            DIGEST=$(curl -s -H "Authorization: Bearer ${TOKEN}" -H "Accept: application/vnd.oci.image.index.v1+json" \
+              "https://ghcr.io/v2/${OWNER}/${{ env.GHCR_REPO }}/tags/list" | jq -r ".manifest.${{ env.GR_VERSION }}-${arch}-alpine.digest")
+
+            if [ -n "$DIGEST" ] && [ "$DIGEST" != "null" ]; then
+              curl -X DELETE -H "Authorization: Bearer ${TOKEN}" "https://ghcr.io/v2/${OWNER}/${{ env.GHCR_REPO }}/manifests/${DIGEST}" \
+                || echo "Failed to delete ${arch} alpine tag"
+            else
+              echo "No matching alpine tag found for ${arch}"
+            fi
+          done
+
+          # delete debian-intermediate tags
+          for arch in amd64 arm64; do
+            IMAGE_URL="https://ghcr.io/v2/${OWNER}/${{ env.GHCR_REPO }}/manifests/${{ env.GR_VERSION }}-${arch}-debian"
+            DIGEST=$(curl -s -H "Authorization: Bearer ${TOKEN}" -H "Accept: application/vnd.oci.image.index.v1+json" \
+              "https://ghcr.io/v2/${OWNER}/${{ env.GHCR_REPO }}/tags/list" | jq -r ".manifest.${{ env.GR_VERSION }}-${arch}-debian.digest")
+
+            if [ -n "$DIGEST" ] && [ "$DIGEST" != "null" ]; then
+              curl -X DELETE -H "Authorization: Bearer ${TOKEN}" "https://ghcr.io/v2/${OWNER}/${{ env.GHCR_REPO }}/manifests/${DIGEST}" \
+                || echo "Failed to delete ${arch} debian tag"
+            else
+              echo "No matching debian tag found for ${arch}"
+            fi
           done
 
       #- name: Verify Image
